version: '3'

services:
#  shared-img:
#    build: .
#    image: shared-img:latest

#  reddit:
#    build: cmd/reddit/
#    ports:
#      - 8080:8080
#    networks:
#      - all
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "guest"
      MYSQL_DATABASE: reddit
    ports:
      - '3306:3306'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/'

  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=reddit
    ports:
      - '27017-27019:27017-27019'
#networks:
#  all: